//! Known v41 medal identities from the pinned LevelUp empirical pair table.
//! Unknown pairs remain unknown; metadata alone never identifies a medal.

/// A medal identity inferred from the summary type/metadata pair. These codes
/// are film codes, not Halo service medal NameIds or localized display labels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Medal {
    Killjoy,
    StoppedShort,
    FlagJoust,
    Spotter,
    TreasureHunter,
    Saboteur,
    Wingman,
    Wheelman,
    Gunner,
    Driver,
    Pilot,
    Tanker,
    Rifleman,
    Bomber,
    Grenadier,
    Boxer,
    Warrior,
    Gunslinger,
    Scattergunner,
    Sharpshooter,
    Marksman,
    Heavy,
    Bodyguard,
    BackSmack,
    Dogfight,
    Harpoon,
    OdinsRaven,
    Skyjack,
    Stick,
    Kong,
    Reversal,
    Snipe,
    GuardianAngel,
    ChainReaction,
    FlyinHigh,
    FromTheGrave,
    LastShot,
    MountUp,
    QuickDraw,
    Reclaimer,
    SpecialDelivery,
    AlwaysRotating,
    Splatter,
    ClashOfKings,
    WatchTheThrone,
    Breacher,
    HangUp,
    CallBlocked,
    DoubleKill,
    KillingSpree,
    GoalLineStand,
    Bulltrue,
    ClusterLuck,
    MindTheGap,
    Pancake,
    Rideshare,
    TagAndBag,
    Whiplash,
    WindshieldWiper,
    HailMary,
    NadeShot,
    Perfect,
    BankShot,
    FireAndForget,
    Ballista,
    Pull,
    NoScope,
    DeathRace,
    FromTheVoid,
    GrappleJack,
    HoldThis,
    Lawnmower,
    OffTheRack,
    PineappleExpress,
    RammingSpeed,
    ShotCaller,
    YardSale,
    Fumble,
    BigDeal,
    HillGuardian,
    ClockStop,
    MountedAndLoaded,
    CounterSnipe,
    DrivingSpree,
    SecureLine,
    ClearReception,
    TripleKill,
    KillingFrenzy,
    FlawlessVictory,
    Steaktacular,
    BoomBlock,
    ReturnToSender,
    AutopilotEngaged,
    SneakKing,
    AchillesSpine,
    GrandSlam,
    Interlinked,
    ThreeSixty,
    CombatEvolved,
    DeadlyCatch,
    StreetSweeper,
    StraightBalling,
    ContractKiller,
    AllThatJuice,
    DeathCabbie,
    BlindFire,
    Perfection,
    Extermination,
    Ninja,
    Quigley,
    RemoteDetonation,
    Fastball,
    RunningRiot,
    Rampage,
    Overkill,
    Nightmare,
    Killtacular,
    Killtrocity,
    Boogeyman,
    Killamanjaro,
    Killtastrophe,
    GrimReaper,
    Killpocalypse,
    Demon,
    Unknown { type_code: u8, medal_code: u8 },
}

impl Medal {
    /// Resolve only a measured pair; never fall back to a neighboring code.
    pub fn from_codes(type_code: u8, medal_code: u8) -> Self {
        match (type_code, medal_code) {
            (50, 26) => Self::Killjoy,
            (50, 36) => Self::StoppedShort,
            (50, 37) => Self::FlagJoust,
            (50, 62) => Self::Spotter,
            (50, 63) => Self::TreasureHunter,
            (50, 64) => Self::Saboteur,
            (50, 65) => Self::Wingman,
            (50, 66) => Self::Wheelman,
            (50, 67) => Self::Gunner,
            (50, 68) => Self::Driver,
            (50, 69) => Self::Pilot,
            (50, 70) => Self::Tanker,
            (50, 71) => Self::Rifleman,
            (50, 72) => Self::Bomber,
            (50, 73) => Self::Grenadier,
            (50, 74) => Self::Boxer,
            (50, 75) => Self::Warrior,
            (50, 76) => Self::Gunslinger,
            (50, 77) => Self::Scattergunner,
            (50, 78) => Self::Sharpshooter,
            (50, 79) => Self::Marksman,
            (50, 80) => Self::Heavy,
            (50, 81) => Self::Bodyguard,
            (50, 82) => Self::BackSmack,
            (50, 87) => Self::Dogfight,
            (50, 88) => Self::Harpoon,
            (50, 91) => Self::OdinsRaven,
            (50, 97) => Self::Skyjack,
            (50, 98) => Self::Stick,
            (50, 101) => Self::Kong,
            (50, 105) => Self::Reversal,
            (50, 108) => Self::Snipe,
            (50, 117) => Self::GuardianAngel,
            (50, 120) => Self::ChainReaction,
            (50, 126) => Self::FlyinHigh,
            (50, 127) => Self::FromTheGrave,
            (50, 131) => Self::LastShot,
            (50, 133) => Self::MountUp,
            (50, 135) => Self::QuickDraw,
            (50, 139) => Self::Reclaimer,
            (50, 142) => Self::SpecialDelivery,
            (50, 151) => Self::AlwaysRotating,
            (50, 156) => Self::Splatter,
            (50, 157) => Self::ClashOfKings,
            (50, 160) => Self::WatchTheThrone,
            (50, 165) => Self::Breacher,
            (51, 178) => Self::HangUp,
            (52, 179) => Self::CallBlocked,
            (100, 0) => Self::DoubleKill,
            (100, 9) => Self::KillingSpree,
            (100, 38) => Self::GoalLineStand,
            (100, 85) => Self::Bulltrue,
            (100, 86) => Self::ClusterLuck,
            (100, 89) => Self::MindTheGap,
            (100, 92) => Self::Pancake,
            (100, 96) => Self::Rideshare,
            (100, 99) => Self::TagAndBag,
            (100, 100) => Self::Whiplash,
            (100, 104) => Self::WindshieldWiper,
            (100, 106) => Self::HailMary,
            (100, 107) => Self::NadeShot,
            (100, 109) => Self::Perfect,
            (100, 110) => Self::BankShot,
            (100, 111) => Self::FireAndForget,
            (100, 112) => Self::Ballista,
            (100, 113) => Self::Pull,
            (100, 114) => Self::NoScope,
            (100, 119) => Self::DeathRace,
            (100, 128) => Self::FromTheVoid,
            (100, 129) => Self::GrappleJack,
            (100, 130) => Self::HoldThis,
            (100, 132) => Self::Lawnmower,
            (100, 134) => Self::OffTheRack,
            (100, 137) => Self::PineappleExpress,
            (100, 138) => Self::RammingSpeed,
            (100, 140) => Self::ShotCaller,
            (100, 141) => Self::YardSale,
            (100, 146) => Self::Fumble,
            (100, 150) => Self::BigDeal,
            (100, 152) => Self::HillGuardian,
            (100, 153) => Self::ClockStop,
            (100, 166) => Self::MountedAndLoaded,
            (100, 168) => Self::CounterSnipe,
            (100, 174) => Self::DrivingSpree,
            (101, 154) => Self::SecureLine,
            (101, 180) => Self::ClearReception,
            (150, 1) => Self::TripleKill,
            (150, 10) => Self::KillingFrenzy,
            (150, 31) => Self::FlawlessVictory,
            (150, 32) => Self::Steaktacular,
            (150, 84) => Self::BoomBlock,
            (150, 95) => Self::ReturnToSender,
            (150, 102) => Self::AutopilotEngaged,
            (150, 103) => Self::SneakKing,
            (150, 115) => Self::AchillesSpine,
            (150, 116) => Self::GrandSlam,
            (150, 118) => Self::Interlinked,
            (150, 121) => Self::ThreeSixty,
            (150, 122) => Self::CombatEvolved,
            (150, 123) => Self::DeadlyCatch,
            (150, 143) => Self::StreetSweeper,
            (150, 148) => Self::StraightBalling,
            (150, 158) => Self::ContractKiller,
            (150, 162) => Self::AllThatJuice,
            (150, 175) => Self::DeathCabbie,
            (150, 177) => Self::BlindFire,
            (200, 13) => Self::Perfection,
            (200, 44) => Self::Extermination,
            (200, 90) => Self::Ninja,
            (200, 93) => Self::Quigley,
            (200, 94) => Self::RemoteDetonation,
            (200, 125) => Self::Fastball,
            (205, 11) => Self::RunningRiot,
            (210, 12) => Self::Rampage,
            (220, 2) => Self::Overkill,
            (220, 27) => Self::Nightmare,
            (225, 3) => Self::Killtacular,
            (230, 4) => Self::Killtrocity,
            (230, 28) => Self::Boogeyman,
            (235, 5) => Self::Killamanjaro,
            (240, 6) => Self::Killtastrophe,
            (240, 29) => Self::GrimReaper,
            (245, 7) => Self::Killpocalypse,
            (250, 30) => Self::Demon,
            _ => Self::Unknown {
                type_code,
                medal_code,
            },
        }
    }

    /// English reference identity, not a localized UI label. None for unknown pairs.
    pub fn name(self) -> Option<&'static str> {
        match self {
            Self::Killjoy => Some("Killjoy"),
            Self::StoppedShort => Some("Stopped Short"),
            Self::FlagJoust => Some("Flag Joust"),
            Self::Spotter => Some("Spotter"),
            Self::TreasureHunter => Some("Treasure Hunter"),
            Self::Saboteur => Some("Saboteur"),
            Self::Wingman => Some("Wingman"),
            Self::Wheelman => Some("Wheelman"),
            Self::Gunner => Some("Gunner"),
            Self::Driver => Some("Driver"),
            Self::Pilot => Some("Pilot"),
            Self::Tanker => Some("Tanker"),
            Self::Rifleman => Some("Rifleman"),
            Self::Bomber => Some("Bomber"),
            Self::Grenadier => Some("Grenadier"),
            Self::Boxer => Some("Boxer"),
            Self::Warrior => Some("Warrior"),
            Self::Gunslinger => Some("Gunslinger"),
            Self::Scattergunner => Some("Scattergunner"),
            Self::Sharpshooter => Some("Sharpshooter"),
            Self::Marksman => Some("Marksman"),
            Self::Heavy => Some("Heavy"),
            Self::Bodyguard => Some("Bodyguard"),
            Self::BackSmack => Some("Back Smack"),
            Self::Dogfight => Some("Dogfight"),
            Self::Harpoon => Some("Harpoon"),
            Self::OdinsRaven => Some("Odin's Raven"),
            Self::Skyjack => Some("Skyjack"),
            Self::Stick => Some("Stick"),
            Self::Kong => Some("Kong"),
            Self::Reversal => Some("Reversal"),
            Self::Snipe => Some("Snipe"),
            Self::GuardianAngel => Some("Guardian Angel"),
            Self::ChainReaction => Some("Chain Reaction"),
            Self::FlyinHigh => Some("Flyin' High"),
            Self::FromTheGrave => Some("From the Grave"),
            Self::LastShot => Some("Last Shot"),
            Self::MountUp => Some("Mount Up"),
            Self::QuickDraw => Some("Quick Draw"),
            Self::Reclaimer => Some("Reclaimer"),
            Self::SpecialDelivery => Some("Special Delivery"),
            Self::AlwaysRotating => Some("Always Rotating"),
            Self::Splatter => Some("Splatter"),
            Self::ClashOfKings => Some("Clash of Kings"),
            Self::WatchTheThrone => Some("Watch the Throne"),
            Self::Breacher => Some("Breacher"),
            Self::HangUp => Some("Hang Up"),
            Self::CallBlocked => Some("Call Blocked"),
            Self::DoubleKill => Some("Double Kill"),
            Self::KillingSpree => Some("Killing Spree"),
            Self::GoalLineStand => Some("Goal Line Stand"),
            Self::Bulltrue => Some("Bulltrue"),
            Self::ClusterLuck => Some("Cluster Luck"),
            Self::MindTheGap => Some("Mind the Gap"),
            Self::Pancake => Some("Pancake"),
            Self::Rideshare => Some("Rideshare"),
            Self::TagAndBag => Some("Tag & Bag"),
            Self::Whiplash => Some("Whiplash"),
            Self::WindshieldWiper => Some("Windshield Wiper"),
            Self::HailMary => Some("Hail Mary"),
            Self::NadeShot => Some("Nade Shot"),
            Self::Perfect => Some("Perfect"),
            Self::BankShot => Some("Bank Shot"),
            Self::FireAndForget => Some("Fire & Forget"),
            Self::Ballista => Some("Ballista"),
            Self::Pull => Some("Pull"),
            Self::NoScope => Some("No Scope"),
            Self::DeathRace => Some("Death Race"),
            Self::FromTheVoid => Some("From the Void"),
            Self::GrappleJack => Some("Grapple-jack"),
            Self::HoldThis => Some("Hold This"),
            Self::Lawnmower => Some("Lawnmower"),
            Self::OffTheRack => Some("Off the Rack"),
            Self::PineappleExpress => Some("Pineapple Express"),
            Self::RammingSpeed => Some("Ramming Speed"),
            Self::ShotCaller => Some("Shot Caller"),
            Self::YardSale => Some("Yard Sale"),
            Self::Fumble => Some("Fumble"),
            Self::BigDeal => Some("Big Deal"),
            Self::HillGuardian => Some("Hill Guardian"),
            Self::ClockStop => Some("Clock Stop"),
            Self::MountedAndLoaded => Some("Mounted & Loaded"),
            Self::CounterSnipe => Some("Counter-snipe"),
            Self::DrivingSpree => Some("Driving Spree"),
            Self::SecureLine => Some("Secure Line"),
            Self::ClearReception => Some("Clear Reception"),
            Self::TripleKill => Some("Triple Kill"),
            Self::KillingFrenzy => Some("Killing Frenzy"),
            Self::FlawlessVictory => Some("Flawless Victory"),
            Self::Steaktacular => Some("Steaktacular"),
            Self::BoomBlock => Some("Boom Block"),
            Self::ReturnToSender => Some("Return to Sender"),
            Self::AutopilotEngaged => Some("Autopilot Engaged"),
            Self::SneakKing => Some("Sneak King"),
            Self::AchillesSpine => Some("Achilles Spine"),
            Self::GrandSlam => Some("Grand Slam"),
            Self::Interlinked => Some("Interlinked"),
            Self::ThreeSixty => Some("360"),
            Self::CombatEvolved => Some("Combat Evolved"),
            Self::DeadlyCatch => Some("Deadly Catch"),
            Self::StreetSweeper => Some("Street Sweeper"),
            Self::StraightBalling => Some("Straight Balling"),
            Self::ContractKiller => Some("Contract Killer"),
            Self::AllThatJuice => Some("All That Juice"),
            Self::DeathCabbie => Some("Death Cabbie"),
            Self::BlindFire => Some("Blind Fire"),
            Self::Perfection => Some("Perfection"),
            Self::Extermination => Some("Extermination"),
            Self::Ninja => Some("Ninja"),
            Self::Quigley => Some("Quigley"),
            Self::RemoteDetonation => Some("Remote Detonation"),
            Self::Fastball => Some("Fastball"),
            Self::RunningRiot => Some("Running Riot"),
            Self::Rampage => Some("Rampage"),
            Self::Overkill => Some("Overkill"),
            Self::Nightmare => Some("Nightmare"),
            Self::Killtacular => Some("Killtacular"),
            Self::Killtrocity => Some("Killtrocity"),
            Self::Boogeyman => Some("Boogeyman"),
            Self::Killamanjaro => Some("Killamanjaro"),
            Self::Killtastrophe => Some("Killtastrophe"),
            Self::GrimReaper => Some("Grim Reaper"),
            Self::Killpocalypse => Some("Killpocalypse"),
            Self::Demon => Some("Demon"),
            Self::Unknown { .. } => None,
        }
    }
}

impl std::fmt::Display for Medal {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(name) = self.name() {
            return formatter.write_str(name);
        }
        match self {
            Self::Unknown {
                type_code,
                medal_code,
            } => write!(formatter, "unknown medal ({type_code}, {medal_code})"),
            _ => unreachable!("known medals have names"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn measured_reference_pairs_and_unknown_negative_cases() {
        // Independent empirical TSV from LevelUp, not generated from this lookup.
        let golden = include_str!("../fixtures/medal-pairs-d61443e-v41.tsv");
        let mut count = 0;
        for line in golden
            .lines()
            .filter(|line| !line.starts_with('#') && !line.is_empty())
        {
            let columns: Vec<_> = line.split('\t').collect();
            if columns[0] == "type_hint" {
                continue;
            }
            let medal = Medal::from_codes(columns[0].parse().unwrap(), columns[1].parse().unwrap());
            assert_eq!(medal.name(), Some(columns[2]));
            count += 1;
        }
        assert_eq!(count, 124);
        assert_eq!(Medal::from_codes(50, 156), Medal::Splatter);
        assert_eq!(Medal::from_codes(100, 156).name(), None);
        assert_eq!(Medal::from_codes(50, 255).name(), None);
    }
}
