#!/usr/bin/env python3
"""Generate (or --check) printable tables from the pinned Go runtime."""
import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('go_root', type=Path)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
reference = Path(__file__).resolve().parent
pin = json.loads((reference / 'facts-quote-runtime.json').read_text())
source = args.go_root / 'src/strconv'
for name, digest in pin['files'].items():
    assert hashlib.sha256((source / name).read_bytes()).hexdigest() == digest, name
text = (source / 'isprint.go').read_text()
out = ['// Copyright 2009 The Go Authors. BSD license: reference/GO_LICENSE.txt.',
       '// Pinned Go 1.26.5 strconv printable tables; generated by reference/generate_facts_quote_tables.py.']
for native, rust in [('isPrint16', 'PRINT16'), ('isNotPrint16', 'NOT_PRINT16'),
                     ('isPrint32', 'PRINT32'), ('isNotPrint32', 'NOT_PRINT32')]:
    body = re.search(r'var ' + native + r' = \[\]uint(?:16|32)\{(.*?)\n\}', text, re.S)[1]
    values = re.findall(r'0x[0-9a-fA-F]+', re.sub(r'//[^\n]*', '', body))
    out.append('pub(super) const ' + rust + ': &[u32] = &[\n' + ''.join(
        '    ' + ', '.join(values[i:i+10]) + ',\n' for i in range(0, len(values), 10)) + '];')
rendered = subprocess.run(['rustfmt', '--emit', 'stdout'], input='\n'.join(out)+'\n',
                          text=True, capture_output=True, check=True).stdout
path = reference.parent / 'facts_quote_tables.rs'
if args.check:
    assert path.read_text() == rendered, 'printable table differs'
else:
    path.write_text(rendered)
print('Pinned quote source and printable tables verified')
